import type { Product } from "@/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description: "Premium quality wireless headphones with noise cancellation and 30-hour battery life.",
    price: 199.99,
    originalPrice: 249.99,
    image: "/images/Wireless Bluetooth headphones.jpg",
    category: "Electronics",
    rating: 4.5,
    reviews: 128,
    inStock: true,
    featured: true,
    discount: 20,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Track your health and fitness with this advanced smartwatch featuring GPS and heart rate monitoring.",
    price: 299.99,
    image: "/images/Smartwatch.jpeg",
    category: "Electronics",
    rating: 4.3,
    reviews: 89,
    inStock: true,
    featured: true,
    createdAt: "2024-01-20",
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description: "Comfortable and sustainable organic cotton t-shirt available in multiple colors.",
    price: 29.99,
    image: "/images/organic-cotton-t-shirt-dress-white-front-61fd202ff2476.webp",
    category: "Clothing",
    rating: 4.2,
    reviews: 156,
    inStock: true,
    featured: false,
    createdAt: "2024-02-01",
  },
  {
    id: "4",
    name: "Professional Coffee Maker",
    description: "Brew the perfect cup of coffee with this professional-grade coffee maker.",
    price: 149.99,
    originalPrice: 179.99,
    image: "/images/Coffee Maker.jpeg",
    category: "Home & Garden",
    rating: 4.7,
    reviews: 203,
    inStock: true,
    featured: true,
    discount: 17,
    createdAt: "2024-02-05",
  },
  {
    id: "5",
    name: "Yoga Mat Premium",
    description: "Non-slip premium yoga mat perfect for all types of yoga and exercise.",
    price: 49.99,
    image: "/images/Yoga mat.jpg",
    category: "Sports",
    rating: 4.4,
    reviews: 92,
    inStock: true,
    featured: false,
    createdAt: "2024-02-10",
  },
  {
    id: "6",
    name: "Wireless Phone Charger",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices.",
    price: 39.99,
    image: "/images/wireless phone charger.webp",
    category: "Electronics",
    rating: 4.1,
    reviews: 67,
    inStock: false,
    featured: false,
    createdAt: "2024-02-12",
  },
  {
    id: "7",
    name: "Designer Sunglasses",
    description: "Stylish designer sunglasses with UV protection and polarized lenses.",
    price: 89.99,
    originalPrice: 120.0,
    image: "/images/dervin-leopard-decorated-arms-rimless-rectangle-sunglasses-for-men-and-women-dervin-1.webp",
    category: "Clothing",
    rating: 4.6,
    reviews: 134,
    inStock: true,
    featured: true,
    discount: 25,
    createdAt: "2024-02-15",
  },
  {
    id: "8",
    name: "Gaming Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard designed for gaming with customizable keys.",
    price: 129.99,
    image: "/images/mechanical-gaming-keyboard-87-keys-small.jpg",
    category: "Electronics",
    rating: 4.8,
    reviews: 245,
    inStock: true,
    featured: true,
    createdAt: "2024-02-18",
  },
  {
    id: "9",
    name: "Skincare Set",
    description: "Complete skincare routine set with cleanser, toner, serum, and moisturizer.",
    price: 79.99,
    image: "/images/71wFxez7BvL.jpg",
    category: "Beauty",
    rating: 4.3,
    reviews: 178,
    inStock: true,
    featured: false,
    createdAt: "2024-02-20",
  },
  {
    id: "10",
    name: "Bluetooth Speaker",
    description: "Portable waterproof Bluetooth speaker with 360-degree sound.",
    price: 69.99,
    originalPrice: 89.99,
    image: "/images/JBL-PartyBox-110-160W-Portable-Wireless-Speaker-Front-Left-Angled-View.webp",
    category: "Electronics",
    rating: 4.4,
    reviews: 112,
    inStock: true,
    featured: true,
    discount: 22,
    createdAt: "2024-02-22",
  },
]
